Repository PunishXIV/WrathCombo, pull requests merged in 2024-12, with the labels that each got.

#153 [Core] Added GetTargetHPPercent Limits
  WrathCombo/CustomCombo/Functions/Target.cs
Labels: Fixes

#157 [PVP] RPR Fixes and updates
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvP/RPRPVP.cs
Labels: New Feature, Fixes, Adjustments

#160 [MNK] & [BLM] & [MCH]
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
Labels: New Feature, Fixes

#161 [BRD] Fixes
  WrathCombo/Combos/PvE/BRD/BRD.cs
Labels: Fixes, Adjustments

#154 [PVP] Global Emergency Guard Anti Mash edit
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvP/PVPCommon.cs
Labels: Optimization, New Feature

#163 [PVP] Purify WHM CC
  WrathCombo/Combos/PvP/PVPCommon.cs
  WrathCombo/Window/Functions/UserConfig.cs
Labels: New Feature

#164 [PVP] Nin Seiton Unsealed fix
  WrathCombo/Combos/PvP/NINPVP.cs
Labels: Fixes

#182 [VPR] Serpents Tail standalone option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
Labels: New Feature

#185 [SAM] higanbana
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
  WrathCombo/CustomCombo/Functions/Target.cs
Labels: Adjustments

#187 [SCH] Fix Esuna option not showing
  WrathCombo/Combos/CustomComboPreset.cs
Labels: Fixes

#186 [SMN] Fixed swiftcast egi feature.
  WrathCombo/Combos/PvE/SMN/SMN.cs
Labels: Fixes

#171 [GNB/WAR/Bozja] fixes, adjustments, & new features
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/Content/Bozja.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
Labels: Optimization, New Feature, Fixes, Adjustments

#169 [PVP] [MNK] Riddle of Earth fix and LB option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvP/MNKPVP.cs
Labels: New Feature

#168 [PVP] [DRG] Update
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvP/DRGPVP.cs
Labels: New Feature, Fixes, Adjustments

#158 Fix PCT SimpleMode + Add Preset confilicts
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
Labels: New Feature, Fixes

#190 [Core] Account more widely for player hitbox
  WrathCombo/CustomCombo/Functions/Target.cs
Labels: Fixes

#191 [WAR/GNB] fixes/adjustments
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
Labels: New Feature, Fixes, Adjustments

#192 [MNK] Various
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
Labels: Fixes, Adjustments

#193 [VPR] Various
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Fixes, Adjustments

#196 [Core] Make chat message prefixes more consistent
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/WrathCombo.cs
Labels: Fixes

#197 [UI] Make the Ignore List more consistent
  WrathCombo/Window/Tabs/AutoRotationTab.cs
Labels: Optimization

#198 [Core] Squash warnings
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/PvP/PVPCommon.cs
  WrathCombo/CustomCombo/CustomCombo.cs
  WrathCombo/CustomCombo/Functions/Action.cs
  WrathCombo/Data/ContentCheck.cs
Labels: Fixes

#213 [DRK] Add The Balance opener, move CDF to mitigation, [Core] Add a highlight for mitigation
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Data/ContentCheck.cs
  WrathCombo/Window/Functions/Presets.cs
  WrathCombo/Window/Functions/UserConfig.cs
Labels: New Feature, Fixes

#220 [PvP] BLM Wrath Update
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvP/BLMPVP.cs
Labels: Optimization, Fixes

#221 [DNC] Rework
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/CustomCombo/Functions/Action.cs
  WrathCombo/CustomCombo/WrathOpener.cs
  WrathCombo/Window/Functions/UserConfig.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization, New Feature, Fixes, Adjustments

#188 [Core] [IPC] Add IPC
  README.md
  WrathCombo/AutoRotation/AutoRotationConfig.cs
  WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/CustomCombo/Functions/Misc.cs
  WrathCombo/Services/IPC/Enums.cs
  WrathCombo/Services/IPC/HelpAutoRotConfig.cs
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Leasing.cs
  WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/Services/IPC/Search.cs
  WrathCombo/Services/IPC/UIHelper.cs
  WrathCombo/Window/Functions/Presets.cs
  WrathCombo/Window/Tabs/AutoRotationTab.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
  WrathCombo/WrathCombo.cs
  res/ipc_status.txt
Labels: New Feature

#203 [Core] Squash warnings
  WrathCombo/WrathCombo.cs
Labels: Fixes

#225 [BLM] + [MCH] Updates
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
Labels: Optimization, New Feature, Adjustments

#204 [UI] Fix PvP font scaling to match PvE
  WrathCombo/Window/Tabs/PvPFeatures.cs
Labels: Fixes

#217 [Docs] Contributing Guide
  CONTRIBUTING.md
  README.md
Labels: New Feature

#207 [MNK] few fixes
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
Labels: Fixes, Adjustments

#218 [BRD] Fixes and Tweak
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD_Config.cs
Labels: Fixes, Adjustments

#219 [NIN] Ninja weaving and ninki fixes
  WrathCombo/Combos/PvE/NIN/NIN.cs
Labels: Fixes, Adjustments

#226 [PLD] Possible Low FPS Fix
  WrathCombo/Combos/PvE/PLD/PLD.cs
Labels: Fixes

#227 [PvP] RDM Wrath Update
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvP/RDMPVP.cs
Labels: Optimization, Fixes

#228 [Core] Squash compiler warnings
  WrathCombo/Data/ContentCheck.cs
  WrathCombo/Window/Functions/UserConfig.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
Labels: Fixes

#230 [PvP] Misc. Fixes
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvP/BLMPVP.cs
  WrathCombo/Combos/PvP/SAMPVP.cs
  WrathCombo/Combos/PvP/VPRPVP.cs
Labels: New Feature, Fixes, Adjustments

#233 [Core] Fix `set` and `toggle` commands
  WrathCombo/WrathCombo.cs
Labels: Fixes

#232 [IPC] Callback fixes
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/UIHelper.cs
Labels: Fixes

#238 [WAR] Fix Action for Inner Release
  WrathCombo/Combos/PvE/WAR/WAR.cs
Labels: Fixes

#240 [GNB] hey hi hello here's some fixes
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
Labels: Fixes, Adjustments

#246 [BLM PVP] Movement Fix for requiring astral fire
  WrathCombo/Combos/PvP/BLMPVP.cs
Labels: Fixes, Adjustments

#247 [VPR] Reawaken Legacy option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Fixes, Adjustments

#248 [SMN] Add movement and level checks to the Emerald Ruin 3 replacement option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
Labels: Fixes, Adjustments

#251 [BRD] Buff Realignment
  WrathCombo/Combos/PvE/BRD/BRD.cs
Labels: Adjustments

#253 [DNC] Add Simple Modes
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: New Feature, Adjustments

#255 [NIN PVP] Unsealed Seiton Tenchu Health Check
  WrathCombo/Combos/PvP/NINPVP.cs
Labels: Fixes, Adjustments

#256 [Tanks] some good mitigation stuff
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/PLD/PLD_Config.cs
  WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
Labels: New Feature, Adjustments

#249 (MERGE LAST) [Docs] Add CODEOWNERS
  docs/CODEOWNERS
Labels: New Feature
