Repository PunishXIV/WrathCombo, pull requests merged in 2024-11, with the labels that each got.

#57 [MNK] Beast Chakras improvements
  XIVSlothCombo/Combos/PvE/MNK/MNK.cs
Labels: Fixes

#63 [Core] `/wrath` auto-rotation enable and disable commands
  README.md
  XIVSlothCombo/XIVSlothCombo.cs
Labels: New Feature

#62 [Various] Add missing ActionID at end of combo
  XIVSlothCombo/Combos/PvE/DRG/DRG.cs
  XIVSlothCombo/Combos/PvE/MCH/MCH.cs
  XIVSlothCombo/Combos/PvE/RPR/RPR.cs
  XIVSlothCombo/Combos/PvE/SAM/SAM.cs
  XIVSlothCombo/Combos/PvE/VPR/VPR.cs
Labels: Fixes

#70 [RPR] Remove SoD Check
  XIVSlothCombo/Combos/PvE/RPR/RPR.cs
Labels: Fixes

#60 SCH Fairy Reminder, Warning Squash
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/ADV/ADV_Config.cs
  XIVSlothCombo/Combos/PvE/ALL/ALL_Config.cs
  XIVSlothCombo/Combos/PvE/BLU/BLU_Config.cs
  XIVSlothCombo/Combos/PvE/DOH/DOH_Config.cs
  XIVSlothCombo/Combos/PvE/DOL/DOL_Config.cs
  XIVSlothCombo/Combos/PvE/SCH/SCH.cs
Labels: New Feature, Fixes

#71 [GNB] 7.1 minor rotation refactor, mitigation support .. plus some WAR stuff
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/ALL/ALL.cs
  XIVSlothCombo/Combos/PvE/GNB/GNB.cs
  XIVSlothCombo/Combos/PvE/GNB/GNB_Config.cs
  XIVSlothCombo/Combos/PvE/GNB/GNB_Helper.cs
  XIVSlothCombo/Combos/PvE/WAR/WAR.cs
Labels: Optimization, New Feature, Fixes

#72 [PCT] Combined Motifs Update
  XIVSlothCombo/Combos/PvE/PCT/PCT.cs
  XIVSlothCombo/Combos/PvE/PCT/PCT_Config.cs
Labels: New Feature

#98 [WAR] PrimalRendReady fix
  XIVSlothCombo/Combos/PvE/WAR/WAR.cs
Labels: Fixes

#95 [DNC] Dance Partner Reminder
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/DNC/DNC.cs
Labels: New Feature

#74 [SAM] bandaid fix
  XIVSlothCombo/Combos/PvE/SAM/SAM.cs
  XIVSlothCombo/Combos/PvE/SAM/SAM_Config.cs
  XIVSlothCombo/Combos/PvE/SAM/SAM_Helper.cs
Labels: Fixes

#75 [BLM] Add Fire and Ice option
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/BLM/BLM.cs
Labels: New Feature

#76 [RDM] Lucid deprioritize
  XIVSlothCombo/Combos/PvE/RDM/RDM.cs
Labels: Suggestion, Optimization

#80 [PLD] New Mitigation Options, Fixes
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/PLD/PLD.cs
  XIVSlothCombo/Combos/PvE/PLD/PLD_Config.cs
  XIVSlothCombo/CustomCombo/Functions/Target.cs
Labels: New Feature, Fixes

#78 [RDM] Reordered priority of oGCDs in weave window (Fleche > Contre Six > Engagement > Corps-a-corps > ...
  XIVSlothCombo/Combos/PvE/RDM/RDM_Helper.cs
Labels: Optimization

#81 [PvP] 7.1 PvP update
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/AST/AST_Config.cs
  XIVSlothCombo/Combos/PvE/MCH/MCH_Config.cs
  XIVSlothCombo/Combos/PvE/NIN/NIN_Config.cs
  XIVSlothCombo/Combos/PvP/ASTPVP.cs
  XIVSlothCombo/Combos/PvP/BLMPVP.cs
  XIVSlothCombo/Combos/PvP/BRDPVP.cs
  XIVSlothCombo/Combos/PvP/DRKPVP.cs
  XIVSlothCombo/Combos/PvP/GNBPVP.cs
  XIVSlothCombo/Combos/PvP/MCHPVP.cs
  XIVSlothCombo/Combos/PvP/MNKPVP.cs
  XIVSlothCombo/Combos/PvP/NINPVP.cs
  XIVSlothCombo/Combos/PvP/PCTPVP.cs
  XIVSlothCombo/Combos/PvP/PLDPVP.cs
  XIVSlothCombo/Combos/PvP/PVPCommon.cs
  XIVSlothCombo/Combos/PvP/RDMPVP.cs
  XIVSlothCombo/Combos/PvP/RPRPVP.cs
  XIVSlothCombo/Combos/PvP/SAMPVP.cs
  XIVSlothCombo/Combos/PvP/SCHPVP.cs
  XIVSlothCombo/Combos/PvP/SGEPVP.cs
  XIVSlothCombo/Combos/PvP/SMNPvP.cs
  XIVSlothCombo/Combos/PvP/VPRPVP.cs
  XIVSlothCombo/Combos/PvP/WARPVP.cs
  XIVSlothCombo/Combos/PvP/WHMPVP.cs
Labels: Fixes

#84 [BRD & MCH] Aoe Interrupts + Bard changes
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/BRD/BRD.cs
  XIVSlothCombo/Combos/PvE/MCH/MCH.cs
Labels: New Feature

#104 [MCH] Fix autorot weaving
  XIVSlothCombo/Combos/PvE/MCH/MCH.cs
Labels: Fixes

#105 [GNB] AoE & Mitigations fixes/adjustments
  XIVSlothCombo/Combos/PvE/GNB/GNB.cs
  XIVSlothCombo/Combos/PvE/GNB/GNB_Config.cs
  XIVSlothCombo/Combos/PvE/GNB/GNB_Helper.cs
Labels: Fixes

#106 [DNC] Prevent new DP option from bricking Auto-Rotation
  XIVSlothCombo/Combos/PvE/DNC/DNC.cs
Labels: Fixes

#114 [CORE] +`HasWeaved()`
  WrathCombo/Core/PluginAddressResolver.cs
  WrathCombo/Data/ActionWatching.cs
Labels: New Feature

#115 [GNB] more 7.1 fixes/adjustments
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
Labels: Optimization, Fixes

#119 [Core] Misc. Fixes
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvP/PVPCommon.cs
  WrathCombo/CustomCombo/Functions/Party.cs
Labels: Fixes

#122 SMN Weaving fixes for demi attacks.
  WrathCombo/Combos/PvE/SMN/SMN.cs
Labels: Fixes

#124 [VPR] new option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
Labels: New Feature

#131 [BRD] Cleanup and organization
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
Labels: Optimization

#132 [RPR] add gluttony on bloodstalk option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
Labels: New Feature

#139 [DRG] New option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
Labels: New Feature

#145 [Heals] Default Sliders for New Users
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SGE/SGE_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
Labels: Optimization

#140 [MCH] Cleanup after all the merges
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
Labels: Fixes

#147 [PvP] SAM Wrath Update
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvP/SAMPVP.cs
Labels: Optimization, Fixes

#148 [MNK] add %hp brotherhood + RoF
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
Labels: New Feature

#150 PCT Opener update + Fix Autorotation issue
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
Labels: New Feature, Fixes

#143 [PVP] Many fixes and changes. All my pvp prs combined.
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/BRD/BRD_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/NIN/NIN_Config.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN_Config.cs
  WrathCombo/Combos/PvP/ASTPVP.cs
  WrathCombo/Combos/PvP/BLMPVP.cs
  WrathCombo/Combos/PvP/BRDPVP.cs
  WrathCombo/Combos/PvP/DNCPVP.cs
  WrathCombo/Combos/PvP/DRGPVP.cs
  WrathCombo/Combos/PvP/DRKPVP.cs
  WrathCombo/Combos/PvP/GNBPVP.cs
  WrathCombo/Combos/PvP/MNKPVP.cs
  WrathCombo/Combos/PvP/NINPVP.cs
  WrathCombo/Combos/PvP/PLDPVP.cs
  WrathCombo/Combos/PvP/RDMPVP.cs
  WrathCombo/Combos/PvP/RPRPVP.cs
  WrathCombo/Combos/PvP/SMNPvP.cs
  WrathCombo/Combos/PvP/VPRPVP.cs
Labels: Optimization, New Feature, Fixes
