Repository PunishXIV/WrathCombo, pull requests merged in 2025-07, with the labels that each got.

#678 [Core] Squash Errors/Warnings
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/CustomCombo/Functions/Party.cs
Labels: Fixes

#670 [DRK] Use TBN in Simple Modes
  WrathCombo/Combos/PvE/DRK/DRK_ActionLogic.cs
Labels: Fixes

#677 [DNC][DRK] Fix Phantom Actions interfering with opener(etc)
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
Labels: Fixes

#673 [ActionWatching] Class Update
  WrathCombo/Attributes/CustomComboInfoAttribute.cs
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/PvE/NIN/NIN_Helper.cs
  WrathCombo/Commands.cs
  WrathCombo/CustomCombo/Functions/Misc.cs
  WrathCombo/CustomCombo/Functions/Party.cs
  WrathCombo/CustomCombo/Functions/PlayerCharacter.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/Data/StatusCache.cs
  WrathCombo/Extensions/ByteExtensions.cs
  WrathCombo/Extensions/UIntExtensions.cs
Labels: Optimization

#682 [IPC] Switch to new `ComboType` Attributes
  WrathCombo/Attributes/ComboTypeAttributes.cs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Core/Presets.cs
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Search.cs
  WrathCombo/Window/Functions/Presets.cs
Labels: Optimization, New Feature

#685 [OC] weaves and such
  WrathCombo/Combos/PvE/Content/OccultCrescent/OccultCrescent.cs
  WrathCombo/Combos/PvE/Content/OccultCrescent/OccultCrescent_Config.cs
  WrathCombo/Combos/PvE/Content/OccultCrescent/OccultCrescent_Helper.cs
Labels: Fixes, Adjustments

#693 [BLU] MoonFlute Fix
  WrathCombo/Combos/PvE/BLU/BLU.cs
Labels: Fixes

#694 [WHM] Add Only Bosses option to DOT
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
Labels: New Feature

#701 [Docs] Once-over for all IPC documentation, add SND example
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/Window/Tabs/Settings.cs
  docs/IPC.md
  docs/IPCExample.cs
  docs/IPCExample.lua
Labels: New Feature

#702 [Various] some weekly stuffs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
  WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/SMN/SMN_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Fixes, Adjustments

#703 [IPC] Prevent network checks from being problematic
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Provider.cs
Labels: Optimization, Fixes

#706 [UI] Update Sidebar's default size, +min size, +collapse button
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/Window/ConfigWindow.cs
Labels: New Feature

#699 [SGE] Add Standalone retargetted healing options
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
Labels: Optimization, New Feature

#710 [WHM] Priority Treatment
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/Roles/RoleActions.cs
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/Content/Variant/VariantActions.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
  WrathCombo/Core/ActionRetargeting.cs
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/CustomCombo/SimpleTarget.cs
  WrathCombo/Data/StatusCache.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
Labels: New Feature, Adjustments

#717 [DNC] Fix Custom Steps
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: Fixes

#700 [Core] Add more nuanced Plugin Conflicts (MERGE LAST)
  WrathCombo/Attributes/RetargetedAttribute.cs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Core/Presets.cs
  WrathCombo/Data/ConflictingPluginsCheck.cs
  WrathCombo/Data/Conflicts/ConflictingPlugins.cs
  WrathCombo/Data/Conflicts/ConflictingPluginsChecks.cs
  WrathCombo/Data/Conflicts/Conflicts.cs
  WrathCombo/DebugFile.cs
  WrathCombo/Extensions/UIntExtensions.cs
  WrathCombo/Services/IPC Subscriber/IPCSubscriber.cs
  WrathCombo/Services/IPC_Subscriber/AllStaticIPCSubscriptions.cs
  WrathCombo/Services/IPC_Subscriber/BossMod.cs
  WrathCombo/Services/IPC_Subscriber/MOAction.cs
  WrathCombo/Services/IPC_Subscriber/Orbwalker.cs
  WrathCombo/Services/IPC_Subscriber/Reaction.cs
  WrathCombo/Services/IPC_Subscriber/Redirect.cs
  WrathCombo/Services/IPC_Subscriber/ReusableIPC.cs
  WrathCombo/Window/ConfigWindow.cs
  WrathCombo/Window/Functions/Presets.cs
  WrathCombo/WrathCombo.cs
  docs/CODEOWNERS
Labels: New Feature
