Repository PunishXIV/WrathCombo, pull requests merged in 2025-08, with the labels that each got.

#720 [Healers] Various Additions and Fixes
  WrathCombo/Attributes/RetargetedAttribute.cs
  WrathCombo/AutoRotation/AutoRotationConfig.cs
  WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SGE/SGE_Config.cs
  WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
  WrathCombo/Services/IPC/Enums.cs
  WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
  WrathCombo/Window/Tabs/AutoRotationTab.cs
  docs/CODEOWNERS
Labels: Optimization, New Feature

#721 [Various] Edewen DPS Classes Small Cleanups and Additions
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Config.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PCT/PCT_Config.cs
  WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/SMN/SMN_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
Labels: New Feature

#722 [Core] Fix CTD in `TargetIsInvincible`
  WrathCombo/CustomCombo/Functions/Status.cs
  WrathCombo/CustomCombo/Functions/Target.cs
Labels: Fixes

#724 [Various] General code cleanup/BLM - MNK - RPR Updates
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Optimization, Fixes

#730 [AutoRot] Only assign an ST target if using an action
  WrathCombo/AutoRotation/AutoRotationController.cs
Labels: Optimization, Fixes

#729 [7.3 AutoRot] Heal AoE Range increased to 20
  WrathCombo/AutoRotation/AutoRotationController.cs
Labels: Optimization, Fixes

#728 [IPC] Expose `DPSSettings.DPSAoETargets`
  WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
  WrathCombo/Services/IPC/Enums.cs
  WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
  WrathCombo/Services/IPC/UIHelper.cs
  WrathCombo/Window/Tabs/AutoRotationTab.cs
Labels: New Feature

#735 [BRD] Multidotting
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Config.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
  WrathCombo/CustomCombo/SimpleTarget.cs
  WrathCombo/Extensions/UIntExtensions.cs
  docs/BurstHoldingMacros.md
Labels: New Feature

#727 [Core] Added Acceleration Bomb & Pyretics
  WrathCombo/AutoRotation/AutoRotationConfig.cs
  WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/CustomCombo/Functions/Status.cs
  WrathCombo/Data/StatusCache.cs
  WrathCombo/Window/Tabs/AutoRotationTab.cs
Labels: Fixes

#745 [Core] Fix BossModReborn Conflicts
  WrathCombo/Data/Conflicts/ConflictingPlugins.cs
  WrathCombo/Data/Conflicts/ConflictingPluginsChecks.cs
  WrathCombo/Services/IPC_Subscriber/BossMod.cs
Labels: Fixes

#746 [Core] Undo Auto-Rotation Targeting change
  WrathCombo/AutoRotation/AutoRotationController.cs
Labels: Fixes

#747 [WHM] Fix `ReplacedSkill`
  WrathCombo/Combos/CustomComboPreset.cs
Labels: Fixes

#749 [Core] Make Multi-Dot not Pull enemies
  WrathCombo/CustomCombo/SimpleTarget.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
Labels: Fixes

#760 [NIN] Little fixes
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/NIN/NIN_Config.cs
  WrathCombo/Combos/PvE/NIN/NIN_Helper.cs
Labels: Fixes

#761 [Phys Ranged][Core] Raidwide Mits and Bard... Stuff
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Config.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/CustomCombo/Functions/Status.cs
Labels: New Feature, Adjustments

#764 [PVP] 7.3 Update
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvP/ALL/ALL.cs
  WrathCombo/Combos/PvP/ASTPVP.cs
  WrathCombo/Combos/PvP/BLMPVP.cs
  WrathCombo/Combos/PvP/BRDPVP.cs
  WrathCombo/Combos/PvP/DNCPVP.cs
  WrathCombo/Combos/PvP/DRGPVP.cs
  WrathCombo/Combos/PvP/DRKPVP.cs
  WrathCombo/Combos/PvP/GNBPVP.cs
  WrathCombo/Combos/PvP/MCHPVP.cs
  WrathCombo/Combos/PvP/MNKPVP.cs
  WrathCombo/Combos/PvP/NINPVP.cs
  WrathCombo/Combos/PvP/PCTPVP.cs
  WrathCombo/Combos/PvP/PLDPVP.cs
  WrathCombo/Combos/PvP/RDMPVP.cs
  WrathCombo/Combos/PvP/RPRPVP.cs
  WrathCombo/Combos/PvP/SAMPVP.cs
  WrathCombo/Combos/PvP/SCHPVP.cs
  WrathCombo/Combos/PvP/SGEPVP.cs
  WrathCombo/Combos/PvP/SMNPvP.cs
  WrathCombo/Combos/PvP/VPRPVP.cs
  WrathCombo/Combos/PvP/WARPVP.cs
  WrathCombo/Combos/PvP/WHMPVP.cs
  WrathCombo/CustomCombo/SimpleTarget.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
Labels: New Feature, Adjustments

#766 [Core] Fix `AST.JobID` check
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
Labels: Fixes

#768 [Casters] Addles, and standstill timer rdm
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PCT/PCT_Config.cs
  WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
Labels: New Feature

#769 Removed Sprint/Island Sprint actions from ALL
  WrathCombo/Combos/PvE/ALL/ALL.cs
Labels: Adjustments

#770 [Healers] So Simple a Caveman could do it
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/CustomCombo/Functions/Status.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
  docs/CODEOWNERS
Labels: New Feature

#771 [Docs] Fix broken link
  docs/BurstHoldingMacros.md
Labels: Fixes

#774 [Core] Fix `/wrath auto target` Command
  WrathCombo/Commands.cs
Labels: Fixes

#767 [BLM] Standalones
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
Labels: Optimization, Fixes

#772 [Content] Optimize Occult Crescent, introduce `ContentSpecificActions`
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/Content/ContentSpecificActions.cs
  WrathCombo/Combos/PvE/Content/OccultCrescent/OccultCrescent.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
Labels: Optimization, New Feature

#775 [SAM] makeshift basic one button + prio shoha
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
Labels: New Feature, Adjustments

#784 [VPRPVP] LImit break fix for performance mode
  WrathCombo/Combos/PvP/VPRPVP.cs
Labels: Fixes

#785 [NIN] Savage Blade Protection
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/NIN/NIN_Config.cs
  WrathCombo/Combos/PvE/NIN/NIN_Helper.cs
Labels: New Feature

#786 [SCH] Dot Slider fix
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
Labels: Fixes

#788 [RDM] Vercure solo
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
Labels: New Feature

#790 [WHM] Bloodlily trying to pool
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
Labels: Fixes, Adjustments
