Repository PunishXIV/WrathCombo, pull requests merged in 2025-03, with the labels that each got.

#364 [DRK] Fix ST `Salted Earth`, add AoE Mana limit
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
Labels: New Feature, Fixes, Adjustments

#366 [Healers] Dot update
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SGE/SGE_Config.cs
  WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
Labels: Optimization, Adjustments

#367 [PVP] Small fixes
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvP/MNKPVP.cs
  WrathCombo/Combos/PvP/WHMPVP.cs
Labels: Fixes

#370 [DRG] Wyrmwind logic
  WrathCombo/Combos/PvE/DRG/DRG.cs
Labels: Optimization, Adjustments

#371 [Various] Bosschecks
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
Labels: Optimization, New Feature

#373 [DNC] Add range checks, anti-drift recommendation
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: New Feature, Adjustments

#374 [Core] Handle specific-Tab cmds better, add `pve` and `pvp`, add `combo` setting
  README.md
  WrathCombo/Commands.cs
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
  WrathCombo/Window/Tabs/Settings.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization, New Feature, Fixes

#379 [Core] Enable building on *nix systems
  WrathCombo/WrathCombo.csproj
Labels: New Feature

#382 [SGE] Taurochole adjustment
  WrathCombo/Combos/PvE/SGE/SGE.cs
Labels: Adjustments

#383 [RPR] + [VPR] Add positional opener
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Optimization, Adjustments

#386 [WHM] Prevent misonfigured `Regen` spam
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
Labels: Optimization

#387 [RDM] Some `Acceleration` stuff
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
Labels: New Feature

#377 [Core] Apply Stance and Dance Partner
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
  WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
  WrathCombo/CustomCombo/Functions/Status.cs
  WrathCombo/Extensions/UIntExtensions.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization, New Feature

#391 [IPC] Various Fixes, including Freeze
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Leasing.cs
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/Services/IPC/Search.cs
Labels: Fixes

#389 [MNK] Optimization
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
Labels: Optimization

#392 [Core] Fix Stance+Partner upping
  WrathCombo/WrathCombo.cs
Labels: Optimization, Fixes

#393 [PCT] Add option to prioritize instant casts when `Inspiration` and `Hyperphantasia` are active
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PCT/PCT_Config.cs
Labels: New Feature

#394 [RPR] Arcane Circle fixes
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
Labels: Fixes, Adjustments

#395 [UI] Minor fixes
  WrathCombo/Commands.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
  WrathCombo/Window/Tabs/Settings.cs
  WrathCombo/WrathCombo.cs
Labels: Fixes

#397 [IPC] Fixed Class-handling
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Leasing.cs
  WrathCombo/WrathCombo.cs
Labels: Fixes

#399 Add Porta Decumana Vortex Barrier to InvincibleStatus list
  WrathCombo/CustomCombo/Functions/Status.cs
Labels: Fixes

#400 [MCH] Add Battletarget option
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
Labels: New Feature, Adjustments

#401 [VPR] Fix skill usage
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Fixes, Adjustments

#402 [DRK] Skip mit if invuln
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
Labels: Optimization, Fixes, Adjustments

#403 [Core] `/wrath toggle <x>` improvements
  WrathCombo/Commands.cs
Labels: Optimization, New Feature

#404 [UI] Add more recommendations to Settings helpmarkers
  WrathCombo/Window/Tabs/Settings.cs
Labels: New Feature

#420 [GNB] `Scuffed` options
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
Labels: New Feature

#413 [DRK] Improve Dark Arts usage
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
Labels: Fixes, Adjustments

#417 [DNC] Remove the SS->LD and TS->Dv conflict
  WrathCombo/Combos/CustomComboPreset.cs
Labels: Fixes

#415 [RPR] + [MNK] Optimize
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
Labels: Optimization, Adjustments

#410 [Core] Variant Inheritance logic fixes
  WrathCombo/Combos/PvE/Content/Variant.cs
Labels: Fixes, Adjustments
