Repository PunishXIV/WrathCombo, pull requests merged in 2025-02, with the labels that each got.

#314 [DNC] Buffcheck fix
  WrathCombo/Combos/PvE/DNC/DNC.cs
Labels: Fixes, Adjustments

#315 [MCH] Hypercharge conditionals
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
Labels: Optimization, Adjustments

#316 [Tanks] Add interrupt into the combos, [Core] Rework settings tab
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/Window/Tabs/Settings.cs
Labels: New Feature, Adjustments

#318 [Core] Local Image
  WrathCombo/Window/ConfigWindow.cs
Labels: Optimization

#319 [IPC] Fix UI, Add `Set` status codes
  WrathCombo/Services/IPC/Enums.cs
  WrathCombo/Services/IPC/HelpAutoRotConfig.cs
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Leasing.cs
  WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/Window/Tabs/AutoRotationTab.cs
  docs/IPC.md
  docs/IPCExample.cs
Labels: New Feature, Fixes

#320 [DRK] Simple Modes, In-Rotation Mit expansion, Rework
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization, New Feature, Fixes, Adjustments

#323 [WAR/GNB] CustomComboInfo fix .. Aurora fix
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
Labels: Fixes

#327 [VPRPVP] Emergency features / Snake Scales Fix. MCHPVP quickfix.
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvP/MCHPVP.cs
  WrathCombo/Combos/PvP/PVPCommon.cs
Labels: Fixes, Adjustments

#328 [SAM] dynamic meikyo usage
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Labels: Optimization, Adjustments

#331 [MNK] add BH - RoF option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
Labels: New Feature

#332 [RPR] Add soulsow to rotation
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
Labels: New Feature

#333 [DNC] Add `Peloton` back, add Tech openers
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: New Feature, Fixes

#335 [All] Use `All.SavageBlade` over `11`
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLU/BLU.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvP/PVPCommon.cs
  WrathCombo/Combos/PvP/RDMPVP.cs
  WrathCombo/Core/IconReplacer.cs
  WrathCombo/CustomCombo/CustomCombo.cs
  WrathCombo/CustomCombo/WrathOpener.cs
Labels: Adjustments

#362 [Core] Add Manual rotation throttle
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Commands.cs
  WrathCombo/Core/ActionReplacer.cs
  WrathCombo/Core/IconReplacer.cs
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/CustomCombo/Functions/Action.cs
  WrathCombo/CustomCombo/WrathOpener.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/DebugFile.cs
  WrathCombo/Services/Service.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
  WrathCombo/Window/Tabs/Settings.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization, New Feature

#361 [SGE][SCH] Optimize AoE Heals code
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
Labels: Fixes

#360 [Core] Proper erroring for file saving, reduce save spam
  WrathCombo/Combos/PvE/SGE/SGE_Config.cs
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/Window/Functions/Presets.cs
  WrathCombo/Window/Tabs/PvEFeatures.cs
  WrathCombo/Window/Tabs/PvPFeatures.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization, Fixes

#355 Update Other Plugins section to include Questionable
  README.md
Labels: New Feature

#353 [UI] Add button to create Debug file
  WrathCombo/Window/Tabs/Settings.cs
Labels: New Feature

#352 [Core] Add `settings` and `autosettings` commands
  README.md
  WrathCombo/Commands.cs
Labels: New Feature

#351 [Core] Fix `OpenToCurrentJobOnSwitch` running at launch
  WrathCombo/Window/Tabs/PvEFeatures.cs
  WrathCombo/WrathCombo.cs
Labels: Fixes

#350 [Core] Squash compiler warnings
  WrathCombo/Services/IPC Subscriber/IPCSubscriber.cs
  WrathCombo/Window/InfoBox.cs
Labels: Fixes

#347 [Core] Fix interrupt delay checking
  WrathCombo/CustomCombo/Functions/Target.cs
Labels: Fixes

#346 [RPR] Soulsow
  WrathCombo/Combos/PvE/RPR/RPR.cs
Labels: Fixes, Adjustments

#345 [Core] Fix memory error from `HasCleansableDebuff`
  WrathCombo/CustomCombo/Functions/Status.cs
Labels: Fixes

#342 [DRG] Opener + updates
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
Labels: Optimization, New Feature, Adjustments

#341 [Core] `IsBoss`: Handle nullability
  WrathCombo/CustomCombo/Functions/Target.cs
Labels: Fixes

#340 [DNC] New Fan Dance options, various tweaks
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
  WrathCombo/Window/Tabs/Settings.cs
Labels: Optimization, New Feature, Adjustments

#337 [MCH] Add gauss rico pooling
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
Labels: New Feature

#336 [DRK] Fix `Shadowbringer` pooling, AoE combos, Blood-blocking
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/CustomCombo/WrathOpener.cs
Labels: New Feature, Fixes, Adjustments
