Repository PunishXIV/WrathCombo, pull requests merged in 2025-05, with the labels that each got.

#511 [Various] Update gauge usage
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Optimization, Adjustments

#513 [BRD] Interupt Fix
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
Labels: Fixes, Adjustments

#515 [DRK] Prevent Blood from holding up Disesteem
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/Roles/RoleActions.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization, Fixes, Adjustments

#525 [Core] Function Updates
  WrathCombo/CustomCombo/CustomCombo.cs
  WrathCombo/CustomCombo/Functions/Action.cs
  WrathCombo/CustomCombo/Functions/Cooldown.cs
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/Window/Tabs/Debug.cs
Labels: Optimization, Adjustments

#533 [DNC] Resolve more feature conflicts, Various improvements
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: Optimization, New Feature, Fixes, Adjustments

#526 [SMN] Priority selection for Summon Order
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/SMN/SMN_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
Labels: Optimization, Adjustments

#534 [PVP] Fix Out-of-Range Purify issues
  WrathCombo/Combos/PvP/ALL/ALL.cs
  WrathCombo/Window/Functions/UserConfig.cs
Labels: Fixes, Adjustments

#530 [Core] Party UI Target Work
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/CustomCombo/Functions/Party.cs
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/Services/PartyTargetingService.cs
  WrathCombo/Services/PartyUITargeting.cs
  WrathCombo/Window/TargetHelper.cs
Labels: Optimization, Adjustments

#518 [MCH] Fixes AA
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
Labels: New Feature, Fixes

#519 [BLM] Here we go again
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
Labels: Fixes, Adjustments

#523 [DRG] Add doubleweave check
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
Labels: Optimization, Adjustments

#524 [SAM] Fixes
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Labels: Fixes, Adjustments

#532 [VPR] Stuffs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: New Feature, Adjustments

#542 [GNB/WAR] some big boy cleanup
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
Labels: Optimization, New Feature, Fixes, Adjustments

#554 [DNC] Fix `RisingWindmill` before it is level-unlocked
  WrathCombo/Combos/PvE/DNC/DNC.cs
Labels: Fixes, Adjustments

#541 [MCH] fix AoE
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
Labels: Fixes, Adjustments

#544 [DRG] Lifesurge fix
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
Labels: Fixes, Adjustments

#540 [BLM] cleanup + MP check
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
Labels: Fixes, Adjustments

#551 [Tanks] Add Single Target Stun
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
Labels: New Feature, Adjustments

#557 [Data] ReceiveActionEffectDetour Null Fix
  WrathCombo/Data/ActionWatching.cs
Labels: Fixes

#559 [PLD] Operator Precedence Fix
  WrathCombo/Combos/PvE/PLD/PLD.cs
Labels: Fixes

#560 [MCHPvP] Eagle Eye Toggle Fix
  WrathCombo/Combos/PvP/MCHPVP.cs
Labels: Fixes

#543 [Core] Status Cache Consolidation
  WrathCombo/CustomCombo/Functions/Action.cs
  WrathCombo/CustomCombo/Functions/Status.cs
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/Data/CustomComboCache.cs
  WrathCombo/Data/StatusCache.cs
  WrathCombo/DebugFile.cs
  WrathCombo/Extensions/UIntExtensions.cs
  WrathCombo/Window/Tabs/Debug.cs
Labels: Optimization, Adjustments

#561 [GNB] Fix what job One-Button Group Mit is under
  WrathCombo/Combos/CustomComboPreset.cs
Labels: Fixes

#570 [DRK] Add `Hard Slash` Opener Option as well
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
Labels: New Feature

#566 [IPC] Handle IPv6 better
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/WrathCombo.cs
Labels: Fixes

#556 [PCT] 7.2 Pictoverhaul
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PCT/PCT_Config.cs
  WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
Labels: Optimization, New Feature, Adjustments

#539 [Core] Add Retargeting and `SimpleTarget`, consolidate target logic
  .gitignore
  CONTRIBUTING.md
  WrathCombo/Attributes/RetargetedAttribute.cs
  WrathCombo/Attributes/RoleAttribute.cs
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvE/ALL/HealRetargeting.cs
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SGE/SGE_Config.cs
  WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
  WrathCombo/Core/ActionReplacer.cs
  WrathCombo/Core/ActionRetargeting.cs
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/Core/Presets.cs
  WrathCombo/CustomCombo/CustomCombo.cs
  WrathCombo/CustomCombo/Functions/Action.cs
  WrathCombo/CustomCombo/Functions/Party.cs
  WrathCombo/CustomCombo/Functions/PlayerCharacter.cs
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/CustomCombo/SimpleTarget.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
  WrathCombo/Extensions/UIntExtensions.cs
  WrathCombo/Services/PartyUITargeting.cs
  WrathCombo/Services/PronounService.cs
  WrathCombo/Window/Functions/Presets.cs
  WrathCombo/Window/Functions/UserConfig.cs
  WrathCombo/Window/MajorChangesWindow.cs
  WrathCombo/Window/SettingChangeWindow.cs
  WrathCombo/Window/Tabs/Debug.cs
  WrathCombo/Window/Tabs/Settings.cs
  WrathCombo/Window/TargetHelper.cs
  WrathCombo/WrathCombo.cs
  docs/CODEOWNERS
  docs/IPC.md
  docs/Retargeting.md
  docs/RetargetingExample.cs
  pluginmaster.json
Labels: New Feature, Adjustments

#585 [PLD] Fix Fight or Flight Blocking AoE Modes
  WrathCombo/Combos/PvE/PLD/PLD.cs
Labels: Fixes

#587 [BRD] Retargetted Warden's Paeon
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
Labels: New Feature

#588 [AST] Improve Card target-picking reliability
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
Labels: Fixes
