Repository PunishXIV/WrathCombo, pull requests merged in 2025-09, with the labels that each got.

#800 [Retargeting] Better Ground-Targeted Placement
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
Labels: New Feature

#807 [UI] Add Resetting to Priority Inputs
  WrathCombo/CustomCombo/Functions/Config.cs
  WrathCombo/Window/Functions/UserConfig.cs
Labels: New Feature

#816 [SAM] Standalone updates
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Labels: New Feature, Fixes

#818 [AutoRot] Invincibles / Disengages
  WrathCombo/CustomCombo/Functions/Status.cs
  WrathCombo/Data/StatusCache.cs
Labels: Adjustments

#823 [Various] Little fixes
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
  WrathCombo/Combos/PvP/SGEPVP.cs
Labels: Fixes, Adjustments
