Repository PunishXIV/WrathCombo, pull requests merged in 2025-04, with the labels that each got.

#427 [Core] Removed legacy IsEnabled(uint). ActionReady handles it now.
  WrathCombo/Combos/PvE/Content/Variant.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/CustomCombo/Functions/Cooldown.cs
Labels: Adjustments

#429 [MCH] Fix 1-2-3 after Hypercharge
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
Labels: Fixes, Adjustments

#430 [SAM] add Senei - Guren standalone option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Labels: New Feature

#438 [PVP][Melee] Added Option Role Action Smite, Moved pvp configs to pvp file
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/NIN/NIN_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
  WrathCombo/Combos/PvP/DRGPVP.cs
  WrathCombo/Combos/PvP/MNKPVP.cs
  WrathCombo/Combos/PvP/NINPVP.cs
  WrathCombo/Combos/PvP/RPRPVP.cs
  WrathCombo/Combos/PvP/SAMPVP.cs
  WrathCombo/Combos/PvP/VPRPVP.cs
  WrathCombo/Window/Functions/Presets.cs
  WrathCombo/Window/Functions/UserConfig.cs
Labels: New Feature, Adjustments

#449 [IPC] Add initial caching back
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Provider.cs
Labels: Fixes

#441 [MNK] Optimize PB combo
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
Labels: Optimization, Adjustments

#445 [PVP][Healer] PVP role actions, Moved pvp config to pvp files
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SGE/SGE_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvP/ASTPVP.cs
  WrathCombo/Combos/PvP/SCHPVP.cs
  WrathCombo/Combos/PvP/SGEPVP.cs
  WrathCombo/Combos/PvP/WHMPVP.cs
  WrathCombo/Window/Functions/Presets.cs
Labels: New Feature, Adjustments

#447 [GNB] stuff
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
Labels: Fixes, Adjustments

#448 [PVP][Tanks] Added defensive role action Rampart, Move pvp config to pvp files
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/PLD/PLD_Config.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Combos/PvP/ALL/RoleActions.cs
  WrathCombo/Combos/PvP/DRKPVP.cs
  WrathCombo/Combos/PvP/GNBPVP.cs
  WrathCombo/Combos/PvP/PLDPVP.cs
  WrathCombo/Combos/PvP/WARPVP.cs
  WrathCombo/Window/Functions/Presets.cs
Labels: New Feature, Adjustments

#459 [VRP] Various
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Optimization, New Feature

#452 [PVP][Casters] PVP role action and move pvp config to pvp file
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/PCT/PCT_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN_Config.cs
  WrathCombo/Combos/PvP/BLMPVP.cs
  WrathCombo/Combos/PvP/PCTPVP.cs
  WrathCombo/Combos/PvP/RDMPVP.cs
  WrathCombo/Combos/PvP/SMNPvP.cs
  WrathCombo/Window/Functions/Presets.cs
Labels: New Feature, Adjustments

#440 [AutoRot] null checks....I hope
  WrathCombo/AutoRotation/AutoRotationController.cs
Labels: Adjustments

#442 [Healer] Fix DOT threshold
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
Labels: Fixes

#458 Removed old Obsolete CanWeaveX(ActionID)
  WrathCombo/CustomCombo/Functions/Action.cs
Labels: Optimization

#462 [IPC] Rebuild caches after job change
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization

#453 [Core] Removing Old UserOptions Code
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/NIN/NIN_Config.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvP/ALL/ALL.cs
  WrathCombo/CustomCombo/Functions/Config.cs
Labels: Adjustments

#463 [Core] Update StancePartner to 7.2
  WrathCombo/CustomCombo/StancePartner.cs
  WrathCombo/WrathCombo.cs
  docs/CODEOWNERS
Labels: Fixes

#482 [WHM] Dot spamming fix
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
Labels: Fixes

#488 [DRK] Minor Improvements
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
Labels: Optimization, Adjustments

#485 [BLM] More stuffs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
Labels: Optimization, New Feature

#489 [SAM] Better meikyo usage
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Labels: Optimization, Adjustments

#491 [AST] Card pooling options
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/AST/AST.cs
Labels: Optimization, New Feature, Adjustments

#493 [WHM & SGE] Regen and shield fixes
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
Labels: Fixes

#495 [DRK] Fix Pre-Burst mana saving holding up everything, various optimizations
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/CustomCombo/Functions/Cooldown.cs
Labels: Optimization, Fixes, Adjustments

#496 [Core] Removed old Status Effect functions
  WrathCombo/Combos/PvP/BLMPVP.cs
  WrathCombo/Combos/PvP/NINPVP.cs
  WrathCombo/Combos/PvP/PCTPVP.cs
  WrathCombo/Combos/PvP/RDMPVP.cs
  WrathCombo/Combos/PvP/SAMPVP.cs
  WrathCombo/Combos/PvP/SMNPvP.cs
  WrathCombo/Combos/PvP/VPRPVP.cs
  WrathCombo/CustomCombo/Functions/Config.cs
  WrathCombo/CustomCombo/Functions/Status.cs
Labels: Fixes

#498 [Core] Accept job parameters to the `list` commands
  README.md
  WrathCombo/Commands.cs
Labels: Optimization

#499 [Core] New setting: always open Wrath to the PvE Features tab
  WrathCombo/Commands.cs
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/Data/ContentCheck.cs
  WrathCombo/Window/Tabs/Settings.cs
Labels: New Feature

#500 [BRD] Radiant tweaks and missing option
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
Labels: Optimization, Fixes

#505 [Various] Add Basic combo's
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
Labels: New Feature

#490 [Various] Remove uneeded checks
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Optimization, Adjustments

#507 [PhysRanged] HeadGraze ActionReady'd
  WrathCombo/Combos/PvE/ALL/Roles/RoleActions.cs
Labels: Adjustments

#508 [Core] Re-Squash warnings
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: Fixes

#509 [Core] Add a couple Debug commands to help people with wine
  WrathCombo/Commands.cs
  WrathCombo/DebugFile.cs
  WrathCombo/Window/Tabs/Settings.cs
Labels: New Feature
