Repository PunishXIV/WrathCombo, pull requests merged in 2025-01, with the labels that each got.

#257 [MCH] Queen and Excavator
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
Labels: Optimization, Adjustments

#259 [Tanks] update One-Button Mitigations to have more HP% checks
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/PLD/PLD_Config.cs
  WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
Labels: Adjustments, WIP

#261 [BRD] Fix the raging jaws for simple too
  WrathCombo/Combos/PvE/BRD/BRD.cs
Labels: Fixes, Adjustments

#262 Weaving guardrails (Obsolete use check)
  WrathCombo/CustomCombo/Functions/Action.cs
Labels: Fixes

#258 [Core] Make combo action checks consistent
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DOL/DOL.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
Labels: Fixes

#272 [SCH] Aetherpact's Dissolve Union
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
Labels: New Feature

#277 [RDM] AutoRot Edits, Start of PvP Config
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
  WrathCombo/Combos/PvP/RDMPVP.cs
  WrathCombo/Window/Functions/Presets.cs
Labels: Adjustments

#273 [VPR] Some cleanup
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Adjustments

#271 [GNB] Various Fixes
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
Labels: Fixes

#270 [BRD] Openers and Adjustments
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Config.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
Labels: Optimization, Adjustments

#267 [MNK] Masterful Blitz
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
Labels: New Feature

#264 [MCH] Queen
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
Labels: Optimization, New Feature, Adjustments

#268 [SGE] & [SCH] Various
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SGE/SGE_Config.cs
  WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
Labels: New Feature, Adjustments

#286 [MNK] Dragon Kick added to Solar Lunar Opener
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
Labels: Fixes

#284 [WAR] Fix Primal Combo -> Inner Release
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
Labels: Fixes

#281 [BRD] Remove Radiant Option from CCP
  WrathCombo/Combos/CustomComboPreset.cs
Labels: Adjustments

#280 [MCH] early tools opener
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
Labels: Optimization, New Feature

#276 [Docs] Update IPC docs for recent changes
  docs/IPC.md
Labels: Fixes

#263 [Core] Cleanup
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvE/AST/AST.cs
  WrathCombo/Combos/PvE/AST/AST_Config.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
  WrathCombo/Combos/PvE/BLU/BLU.cs
  WrathCombo/Combos/PvE/BRD/BRD.cs
  WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Config.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
  WrathCombo/Combos/PvE/DOH/DOH.cs
  WrathCombo/Combos/PvE/DOL/DOL.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
  WrathCombo/Combos/PvE/Enums/OpenerState.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/GNB/GNB_Config.cs
  WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/NIN/NIN_Helper.cs
  WrathCombo/Combos/PvE/PCT/PCT.cs
  WrathCombo/Combos/PvE/PCT/PCT_Config.cs
  WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/PLD/PLD_Config.cs
  WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
  WrathCombo/Combos/PvE/SGE/SGE.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/SMN/SMN_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
  WrathCombo/CustomCombo/WrathOpener.cs
Labels: Optimization

#312 [Core] Process Config saves as a queue
  WrathCombo/Core/PluginConfiguration.cs
  WrathCombo/WrathCombo.cs
Labels: Optimization

#291 [WAR] actionID swap
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
Labels: Adjustments

#289 [DRK] More reliable Opener
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
Labels: Optimization

#293 [IPC] Add `OnlyAttackInCombat`, various improvements
  WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
  WrathCombo/Services/IPC/Enums.cs
  WrathCombo/Services/IPC/Helper.cs
  WrathCombo/Services/IPC/Leasing.cs
  WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
  WrathCombo/Services/IPC/Provider.cs
  WrathCombo/Window/Tabs/AutoRotationTab.cs
  WrathCombo/Window/Tabs/Debug.cs
  WrathCombo/WrathCombo.cs
  docs/IPC.md
Labels: New Feature
