Repository PunishXIV/WrathCombo, pull requests merged in 2025-06, with the labels that each got.

#592 [Various] Some Cleanup of my classes
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
Labels: Optimization, Fixes, Adjustments

#596 [DNC] Don't change Partners just because of range
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: Fixes

#597 [WAR] fixes/adjustments
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
Labels: Optimization, Fixes, Adjustments

#599 [Core] Don't Save Debug Configs
  WrathCombo/WrathCombo.cs
Labels: Fixes

#611 [WAR] Fix `Tomahawk` not working in `Simple Mode` with `Include Mitigations` enabled
  WrathCombo/Combos/PvE/WAR/WAR.cs
Labels: Fixes

#613 [WAR] Add `Holmgang` Retargeting
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
Labels: New Feature

#607 [UI] ActionReady and ActionSheet Debug Updates
  WrathCombo/Window/Tabs/Debug.cs
Labels: New Feature

#602 [PLD] Shield bash spam fix
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
Labels: New Feature, Fixes

#604 [WHM] Status Effect Cap Code +Pom Visual fix
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
Labels: Fixes

#606 [BLM] Polyglot usage tweaks
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
Labels: New Feature, Adjustments

#608 [Retargeting] Fix DNC+AST+WHM
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/CustomCombo/Functions/Party.cs
  WrathCombo/CustomCombo/SimpleTarget.cs
  WrathCombo/Data/ActionWatching.cs
  WrathCombo/WrathCombo.cs
Labels: Fixes

#610 [Core] Fix `StatusList` crashes
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/PvE/ALL/HealRetargeting.cs
  WrathCombo/CustomCombo/CustomCombo.cs
  WrathCombo/Data/StatusCache.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
Labels: Fixes

#614 [Various] Status update
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
  WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Labels: Fixes, Adjustments

#618 [SMN] Cleanup 2.0
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SMN/SMN.cs
  WrathCombo/Combos/PvE/SMN/SMN_Config.cs
  WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
Labels: Optimization, New Feature, Adjustments

#620 [WAR] fix `Primal Wrath` triple-weaving
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
Labels: Fixes

#623 [DRK] Updated Blood ability descriptions, various re-organizations and minor improvements
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/DRK/DRK_ActionLogic.cs
  WrathCombo/Combos/PvE/DRK/DRK_Config.cs
  WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
Labels: New Feature, Adjustments

#624 [Tanks] Add Shirk Retargeting Feature, threshold for Double Reprisal Protection
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
  WrathCombo/Combos/PvE/ALL/ALL_Config.cs
  WrathCombo/CustomCombo/SimpleTarget.cs
  WrathCombo/Window/Functions/Presets.cs
  WrathCombo/Window/Tabs/Settings.cs
Labels: New Feature

#625 [Healers] Add Esuna Retargeting Feature
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/ALL/ALL.cs
Labels: New Feature

#626 [UI] Fix Sheet Display Error for System Actions
  WrathCombo/Window/Tabs/Debug.cs
Labels: Fixes

#633 [DNC] Order partners by max hp under any tie
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: Optimization

#634 [TANK] Retargetting Things
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/DRK/DRK.cs
  WrathCombo/Combos/PvE/GNB/GNB.cs
  WrathCombo/Combos/PvE/PLD/PLD.cs
  WrathCombo/Combos/PvE/PLD/PLD_Config.cs
  WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Core/ActionRetargeting.cs
Labels: New Feature

#639 [Core] Add build output directories specific to each OS
  WrathCombo/WrathCombo.csproj
Labels: Fixes

#640 [Jobs] Weekly stuffs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
Labels: New Feature, Fixes, Adjustments

#644 [WHM] Add `Liturgy of the Bell` and `Temperance`
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/WHM/WHM.cs
  WrathCombo/Combos/PvE/WHM/WHM_Config.cs
  WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
Labels: New Feature

#647 [WAR/Core] `Stationary Only` Delay Check + small `DrawSliderFloat` param for decimal places
  WrathCombo/Combos/PvE/WAR/WAR.cs
  WrathCombo/Combos/PvE/WAR/WAR_Config.cs
  WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
  WrathCombo/Window/Functions/UserConfig.cs
Labels: New Feature, Adjustments

#653 [AutoRot][DNC][AST] Fix null error upon entering combat
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/PvE/AST/AST_Helper.cs
  WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Labels: Fixes

#643 [Jobs] weekly stuffs
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/BLM/BLM.cs
  WrathCombo/Combos/PvE/BLM/BLM_Config.cs
  WrathCombo/Combos/PvE/DRG/DRG.cs
  WrathCombo/Combos/PvE/DRG/DRG_Config.cs
  WrathCombo/Combos/PvE/MCH/MCH.cs
  WrathCombo/Combos/PvE/MCH/MCH_Config.cs
  WrathCombo/Combos/PvE/MNK/MNK.cs
  WrathCombo/Combos/PvE/MNK/MNK_Config.cs
  WrathCombo/Combos/PvE/NIN/NIN.cs
  WrathCombo/Combos/PvE/RPR/RPR.cs
  WrathCombo/Combos/PvE/RPR/RPR_Config.cs
  WrathCombo/Combos/PvE/SAM/SAM.cs
  WrathCombo/Combos/PvE/SAM/SAM_Config.cs
  WrathCombo/Combos/PvE/VPR/VPR.cs
  WrathCombo/Combos/PvE/VPR/VPR_Config.cs
Labels: Optimization, Fixes, Adjustments

#650 [RDM] Edmage Overhaul
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/RDM/RDM.cs
  WrathCombo/Combos/PvE/RDM/RDM_Config.cs
  WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
  WrathCombo/WrathCombo.cs
  docs/CODEOWNERS
Labels: Optimization, New Feature, Adjustments

#664 [Core] Add null checking to the last `SimpleTarget`s
  WrathCombo/CustomCombo/SimpleTarget.cs
Labels: Fixes

#665 [SCH] WellReadMage Overhaul
  WrathCombo/Combos/CustomComboPreset.cs
  WrathCombo/Combos/PvE/SCH/SCH.cs
  WrathCombo/Combos/PvE/SCH/SCH_Config.cs
  WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
  docs/CODEOWNERS
Labels: Optimization, New Feature, Adjustments

#666 [Target] Class Revision, Logic Streamlining
  WrathCombo/AutoRotation/AutoRotationController.cs
  WrathCombo/Combos/PvE/DNC/DNC.cs
  WrathCombo/CustomCombo/Functions/Target.cs
  WrathCombo/Extensions/GameObjectExtensions.cs
  WrathCombo/Window/Tabs/Debug.cs
Labels: Optimization
